CREATE DATABASE NOMINA;
USE NOMINA;
CREATE TABLE PUESTOS(
CODIGO_PUESTO VARCHAR(5) PRIMARY KEY,
NOMBRE_PUESTO VARCHAR(20) NOT NULL,
ESTATUS_PUESTO VARCHAR(1) NOT NULL
)ENGINE=INNODB;

CREATE TABLE DEPARTAMENTOS(
CODIGO_DEPARTAMENTO VARCHAR(5) PRIMARY KEY,
NOMBRE_DEPARTAMENTO VARCHAR(20) NOT NULL,
ESTATUS_DEPARTAMENTO VARCHAR(1) NOT NULL
)ENGINE=INNODB;

CREATE TABLE SALARIOS(
CODIGO_SALARIO VARCHAR(5) PRIMARY KEY,
CANTIDAD_SALARIO VARCHAR(20) NOT NULL,
ESTATUS_SALARIO VARCHAR(1) NOT NULL
)ENGINE=INNODB;

CREATE TABLE EMPLEADO(
CODIGO_EMPLEADO VARCHAR(5) PRIMARY KEY,
NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
CUI_EMPLEADO VARCHAR(20) NOT NULL,
CODIGO_PUESTOS VARCHAR(5) NOT NULL,
CODIGO_DEPARTAMENTO VARCHAR(5) NOT NULL,
CODIGO_SALARIO VARCHAR(5) NOT NULL,
codigoEmpleado int(50) not null primary key,
nombreEmpleado varchar(10)not null,
apellidoEmpleado varchar(10)not null,
sueldoEmpleado varchar(10)not null,
estadoEmpleado varchar(8)not null)ENGINE=INNODB;
create table bajasEmpleado(
codigoEmpleado int(50),
nombreEmpleado varchar(10),
apellidoEmpleado varchar(10),
sueldoEmpleado varchar(10),
estadoEmpleado varchar(8) not null,
FOREIGN KEY (CODIGO_PUESTO) REFERENCES PUESTOS(CODIGO_PUESTO),
FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(CODIGO_DEPARTAMENTO),
FOREIGN KEY (CODIGO_SALARIO) REFERENCES SALARIOS(CODIGO_SALARIO),
FOREIGN KEY (codigoEmpleado) REFERENCES baseEmpleados(codigoEmpleado),
FOREIGN KEY (nombreEmpleado) REFERENCES nombreEmpleados(codigoEmpleado),
FOREIGN KEY (apellidoEmpleado) REFERENCES apellidoEmpleados(codigoEmpleado),
FOREIGN KEY (sueldoEmpleado) REFERENCES sueldoEmpleados(codigoEmpleado)
)ENGINE=INNODB;